#!/bin/bash
FILE=omegga-chunks
BASE=$(dirname "$0")
DEBUG=/target/debug/
RELEASE=/target/release/
DIST=/bin/

if test -f "$DEBUG$FILE"; then
    `$BASE$DEBUG$FILE`
elif test -f "$RELEASE$FILE"; then
    `$BASE$RELEASE$FILE`
else 
    `$BASE$DIST$FILE`
fi
