#!/bin/bash
FILE=omegga-chunks
DEBUG=./target/debug/
RELEASE=./target/release/
DIST=./bin/

cd plugins/omegga-chunks
if test -f "$DEBUG$FILE"; then
    `$DEBUG$FILE`
elif test -f "$RELEASE$FILE"; then
    `$RELEASE$FILE`
else 
    `$DIST$FILE`
fi
